### ISSUE TITLE
navbar active button

### ISSUE THREAD

**Issue by Terkea** [Terkea/django_react_template#2]
when you get redirected from one page to another the `Menu.Item` active class doesn't kick in, leaving the current page activated while browsing some other page.

**Comment by vadimstasiev** [comment]
This issue has been fixed in [this commit](https://github.com/Terkea/django_react_template/commit/e52630134d9d5ea9a8f8b818bcfd5d811287af95). The solution was to update the menu with a `selectedKeys` prop with the pathname so that it matches the keys from the Menu.Item.
